# for https://mlbot.net a GitHub bot that automatically labels issues using Kubeflow.
label-alias:
  bug: 'kind/bug'
  feature: 'kind/feature'
  feature_request: 'kind/feature'  
  question: 'kind/question'
